name: flutter_js_chart
description: Flutter Chart for AliothX
version: 0.62.1
homepage : https://github.com/reactspring
repository: https://github.com/reactspring/flutter_js_chart.git
publish_to: none

environment:
  sdk: ">=2.17.0 <3.0.0"

funding:
  - https://www.buymeacoffee.com/fl_chart

dependencies:
  equatable: ^2.0.5
  flutter:
    sdk: flutter

dev_dependencies:
  build_runner: ^2.2.1
  flutter_test:
    sdk: flutter
  mockito: ^5.3.2
  vector_math: ^2.1.2 #Added to use in some generated codes of mockito
  very_good_analysis: ^3.1.0

screenshots:
  - description: 'LineChartSample1 and LineChartSample2'
    path: pub_screenshots/line_chart.jpg
  - description: 'LineChartSample10'
    path: pub_screenshots/line_chart_sample_10.gif
  - description: 'BarChartSample1 and BarChartSample2'
    path: pub_screenshots/bar_chart.jpg
  - description: 'BarChartSample7'
    path: pub_screenshots/bar_chart_sample_7.gif
  - description: 'PieChartSample1, PieChartSample2 and PieChartSample3'
    path: pub_screenshots/pie_chart.jpg
  - description: 'ScatterChartSample2'
    path: pub_screenshots/scatter_chart_sample_2.gif
  - description: 'RadarChartSample1'
    path: pub_screenshots/radar_chart_sample_1.jpg